### ISSUE TITLE
Readiness en live probe for admin deployment

### ISSUE THREAD

**Issue by ToshKoevoets** [openstad/openstad-kubernetes#34]
Readiness en live probe for admin deployment is currently turned off.

Gets a forbidden warning. Probably connected to the basic auth of the container.

**Comment by jaapgorjup** [comment]
You can try to use a TCP readiness check for this if the application is available when the socket is, this works fine.

Example:
```
readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
```

Ofcourse the best is to have a /healthz endpoint that returns the code expected for instance https://github.com/joelwallis/express-healthz
